### ISSUE TITLE
[Q/A] Where is the privacy policy?

### ISSUE THREAD

**Issue by spenserblack** [nickwalton/AIDungeon#230]
## 🤓 Question
On your website, aidungeon.io, it says
>By installing & playing our game you agree to our privacy policy [etc.]

I tried to find this privacy policy on the website \(on mobile\), but couldn't. If I'm not missing something obvious, could you add a link to the privacy policy to the small print?

**Comment by LumiWasTaken** [comment]
https://aidungeon.io/privacy.html

**Comment by spenserblack** [comment]
@sourceengineer Thanks!
