### ISSUE TITLE
[FEAT] /redo

### ISSUE THREAD

**Issue by Iluvalar** [nickwalton/AIDungeon#234]
I looked at the code
303                elif command == "revert" **OR "redo":**
and later
               elif command == "redo":
                            action=action
                            goto 343 //you might have to make a function out of that part, but you get what i mean.
Sorry i can't really code in python, but this pseudo code should be easy to implement for real.

Sometime the AI come up with crazy story line, it would be convenient to cancel it and redo the same action with a single command.

**Comment by Sporking** [comment]
Agreed. AI Dungeon does not make it easy to undo the last response (/revert) and then resubmit the same text.

**Comment by Iluvalar** [comment]
Thank you.
