### ISSUE TITLE
Play on CPU?

### ISSUE THREAD

**Issue by WAUthethird** [nickwalton/AIDungeon#24]
HI! So, I have a pretty beefy computer in terms of everything but the GPU, which is an AMD card. I have 24 gigs of ram and a pretty powerful CPU though.

Would it be possible to modify the code to run on CPU? (and possibly modify scripts to run on Windows without needing Bash?)

I find it annoying whenever I get an OOM error in Colab, so it'd be great if I could run it locally.

Edit: Time is not an issue for me, I just want to run it locally.

**Comment by Akababa** [comment]
have you tried installing regular tensorflow?

**Comment by rusch95** [comment]
I have it currently running with CPU fine.

**Comment by WAUthethird** [comment]
> I have it currently running with CPU fine.

Ohh, I totally forgot that TF bundles the CPU and GPU versions together in one package now.
Thanks!
