### ISSUE TITLE
[FEAT] Add /forget, /update commands

### ISSUE THREAD

**Issue by Sporking** [nickwalton/AIDungeon#244]
## 🚀 Feature Request

The /remember command was recently added to the iPhone app and I’m not sure which others. I would like each use of /remember to generate a new sequential integer in its output, e.g.

> \> turn the sky blue
> The clouds part and the sky is now a beautiful blue color.
> \>/remember The Sky Is Blue.
> ... Added new memory \# 42: ”The Sky Is Blue.”

so that that integer could later be used to remove the added item from the story context.

> \> turn the sky red
> The sky just turned an angry shade of red.
> \>  /forget 42
> ... forgot “The Sky Is Blue”
> \> /remember The Sky Is Red.
> \> ...

It would also be useful to be able to replace (forget old value, remember new value) a context item by specifying its number:

> \> /update 42 The Sky Is Plaid.

**Comment by OrionFive** [comment]
Even better would be a sidebar with all the remembered items and an X button to remove them at any point.

**Comment by Renha** [comment]
context control center! :+1:

**Comment by OrionFive** [comment]
I just saw the browser version does have this. You can just edit the context. So I guess this just needs to be applied to Android / iPhone in some way.

**Comment by Sporking** [comment]
It looks as though it's possible to edit the context on iPhone as well now, and I assume that it will be possible on Android as well, so I'm closing this bug.
