### ISSUE TITLE
[FEAT] Add sorting the search results

### ISSUE THREAD

**Issue by YukiSakuma** [nickwalton/AIDungeon#254]
## 🚀 Feature Request

I've been using the AIDungeon website for a while now but what really bugs me is when I use the search feature I can't seem to find an option to sort the search results like for example sort the results by datetime it was added either in ascending/descending order unless I miss there's actually one?

**Comment by YukiSakuma** [comment]
While they did add a sort option a day later after I posted the issue, you can only sort while in the Explore option. If you search a story/adventure the sort option disappears so the issue is still open because that is what my main OP is all about, aka searching a story/adventure and **_sorting the search results_**.

**Comment by WAUthethird** [comment]
@YukiSakuma This is not the correct place for submitting issues about the webapp. This is purely for the old open-source version.

**Comment by YukiSakuma** [comment]
@WAUthethird
You could be right but the web devs seem to be reading the issues or implementing feat request in reference to my 2nd comment from Apr 19, I just checked the website and the one I originally requested that is "adding an option to sort the search results" is now implemented,

So I think I would close this issue, but if you are right could you link to a proper github for the web app itself?
