### ISSUE TITLE
[BUG] AI never uses double quotes, even when direct dialog is enabled

### ISSUE THREAD

**Issue by OrionFive** [nickwalton/AIDungeon#255]
## 🐛 Bug Report

**Describe the bug**
Since recently, the AI is incredibly weird around speech, as if it's trying to avoid using quotes (" "). So it either uses single quotes for speech or passive voice (He says that ...) or nothing (He says: -and then comes nothing-).
I have an active subscription and I'm aware that there is an option to enable direct dialog. And I would assume that that would cause this behavior when disabled. But it is enabled.

So my guess is that for some reason it's disabled, no matter what.

**How to Reproduce**

1. Start an adventure.
2. Begin a conversation.
3. Watch the weirdness unfold.

**Expected behavior**
Dialog as it used to be (You say "How are you?". He replies: "Fine.").

**Example**
[example.txt](https://github.com/AIDungeon/AIDungeon/files/4468973/example.txt)

**Additional context**
- Via play.aidungeon.io or the app
- Using an enabled subscription (the problem occurs since the subscription update)

**Comment by OrionFive** [comment]
Is this even the right repository for issues with the web or app version?

**Comment by WAUthethird** [comment]
@OrionFive It is not.

**Comment by OrionFive** [comment]
Sorry :P
