### ISSUE TITLE
[BUG]  White screen

### ISSUE THREAD

**Issue by RazorManager89** [nickwalton/AIDungeon#259]
## 🐛 Bug Report

**Describe the bug**
https://play.aidungeon.io loads to a white screen.

**How to Reproduce**

I dinnae what happened. To reproduce it you would just enter the play.aidungeon.io website

**Expected behavior**
AIDungeon loading up.

**Screenshots**

**Additional context**
I was just simply booting up AIDungeon again.

**Comment by deggertsen** [comment]
This issue should be fixed. Are you still seeing it? Also, in the future please submit support requests to support@aidungeon.io
