### ISSUE TITLE
What is winning?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [nickwalton/AIDungeon#42]
Once I had the game declare "YOU WIN!" (the context was something like "you live happily ever after) and automatically save state for me. And once I had it declare

```
You win!
You win!
You win!
```

like 10 times, but it didn't save the game state. (I was assuming the first was a win, and the second was just something it said.)

But more interestingly, what is the condition that leads the game to detect a win? I noticed after the second kind win (where it repeated itself) that everything I did thereafter, it would just echo back to me: 

```
> Invent penicillin.
You invent penicillin.

> Knit the Statue of Liberty in Spanish.
You knit the Statue of Liberty in Spanish.
```

(I'm making that up -- I don't remember what the actual input was, but that's the process that was happening.)

**Comment by nickwalton** [comment]
You just have to get "live happily ever after" to win. :) It's more an Easter egg than anything else.
